#ifndef DEFS_H
#define DEFS_H


#define BUZZER_PIN  6
#define LED_STRIP_PIN 3
#define NUM_LEDS    5

// #define DELAY_BETWEEN_LETTERS_MILLIS 10
// #define DELAY_SPACE_MILLIS 10
// #define DELAY_BETWEEN_MORSE 10
// #define DELAY_END_PHRASE 1000

// #define DOT_DURATION_MILLIS  10
// #define LINE_DURATION_MILLIS 10


#define DELAY_BETWEEN_LETTERS_MILLIS 1000
#define DELAY_SPACE_MILLIS 500
#define DELAY_BETWEEN_MORSE 500
#define DELAY_END_PHRASE 1500

#define DOT_DURATION_MILLIS  100
#define LINE_DURATION_MILLIS 500

#define TONE_FREQUENCY (1000)


int nummber_of_dot_leds;

uint32_t color_led;

#endif /* TEMPLATE_C_H */
